### ISSUE TITLE
Convert all lab systems to api

### ISSUE THREAD

**Issue by sappy5678** [NTHU-NLPLAB/NLPLab_toolkit#2]
[lab systems list](https://www.notion.so/sappy5678/NLPLab-b359b985e55a4d388020d9b25a86e460)

# NLPLab 補完計畫

Created: Jan 18, 2020 2:28 PM

# 說明

把 實驗室的系統都變成 API

# Todo

- [x] Linggle 系列
    - [x] [https://linggle.com](https://linggle.com/)
    - [x] [https://coca.linggle.com](https://coca.linggle.com/) (COCA)
    - [x] [https://zh.linggle.com](https://zh.linggle.com/) (中文 Linggle 中央通訊社)
    - [x] [https://udn.linggle.com](https://udn.linggle.com/) (中文 Linggle 新聞)
    - [x] [https://bi.linggle.com](https://bi.linggle.com/) (TotalPhraseBook)
    - [x] [https://x.linggle.com](https://x.linggle.com) (雙語Linggle)

- [ ] 自動產生文法提示系列
    - [ ] [http://writeahead.nlpweb.org](http://writeahead.nlpweb.org/) （英文 WriteAhead）
    - [ ] [https://whisky.nlplab.cc/smartwrite/](https://whisky.nlplab.cc/smartwrite/) （中文 SmartWrite）

- [ ] 文法改錯與升級系列
    - [ ] [https://whisky.nlplab.cc/](https://whisky.nlplab.cc/) （英文改錯 Cool English）
    - [ ] [http://feedback.linggle.com](http://feedback.linggle.com/) (Linggle Write)
    - [ ] [http://up.linggle.com](http://up.linggle.com/) (Level Up)
    - [ ] [http://why.linggle.com](http://why.linggle.com/) (TellMeWhy 改錯解釋)

- [ ] 閱讀輔助系列
    - [ ] [https://read.linggle.com](https://read.linggle.com/)（Linggle Booster ＋wikification）

- [ ] 語意系列
    - [ ] 中英 WordNet 詞義、例句查詢 LanguageNet [https://whisky.nlplab.cc/langnet/](https://whisky.nlplab.cc/langnet/)
    - [ ] 維基百科對應 WordNet 詞意例句  TextNet [https://textnet.nlplab.cc](https://textnet.nlplab.cc)

**Comment by isaackwok** [comment]
我來認養~
https://bi.linggle.com (TotalPhraseBook)
https://x.linggle.com (雙語Linggle)
